modLoader="javafml" #mandatory
loaderVersion="[47,)" ##mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]]
modId="teamod"
version="1.2.4.1" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/richards-coffee-tea-mod"
displayName="Richard's Coffee and Tea Mod" #mandatory
credits="Glorfindel22/RichardPlaysMC - Programming, Pharade - Many textures & images, LazyGom - Korean Translation"
authors="Glorfindel22 (AKA RichardPlaysMC)"
description='''
Adds coffee, tea, cups, a mortar and pestle, and their plants.
'''
[[dependencies.teamod]]
modId="survive"
mandatory=false
versionRange="[1.20.1-9.0.0,1.20.1-9.0.5]"
ordering="AFTER"
side="BOTH"