modLoader="javafml" #mandatory
loaderVersion="[28,)"
[[mods]]
modId="teamod"
version="1.2.4"
displayName="Richard's Coffee & Tea Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/richards-coffee-tea-mod"
credits="Glorfindel22 (AKA RichardPlaysMC)"
authors="Glorfindel22/RichardPlaysMC - Programming, Pharade - Many textures & images, LazyGom - Korean Translation"
description='''
Adds coffee, tea, cups, a mortar and pestle, and their plants.
'''